### ISSUE TITLE
Selected Item

### ISSUE THREAD

**Issue by qweqwe123** [roomorama/AndroidCountryPicker#6]
Hi 
I use your code

I make a TextView and if I click on it its open on full screen your Countrypicker MainActivity but if I select a country how can I set the text of the TextView to the country name?

How would do you do this?

I want to create a Screen on the Screen is in the top a text then you can select your country but I don´t know how to do.

Please help me.

**Comment by thomasdao** [comment]
you can use listener for that:

``` java
                CountryPicker picker = new CountryPicker();
                picker.setListener(new CountryPickerListener() {

                        @Override
                        public void onSelectCountry(String name, String code) {
                                textView.setText(name);
                        }
                });

```

**Comment by qweqwe123** [comment]
thanks
